server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tp_music?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 10000

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.whf.music.model.domain
  global-config:
    # 数据库相关配置
    db-config:
      # ID自增
      id-type: AUTO

jwt:
  header: Authorization
  secret: abcdefghijklmnopqrstuvwxyz
  # token 过期时间/分钟
  expiration: 30
  prefix: Bearer

ignoreUrls: /login,/register,/resource/**,/swagger-ui/*,/webjars/*,/v3/api-docs/*,/v3/*