<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.whf</groupId>
        <artifactId>music-api</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>music-api-system</artifactId>
    <name>music-api-system</name>
    <description>music-api-system</description>

    <dependencies>
        <dependency>
            <groupId>com.whf</groupId>
            <artifactId>music-common-security</artifactId>
            <version>${revision}</version>
        </dependency>
    </dependencies>
</project>
